_wandb:
    value:
        cli_version: 0.19.9
        m: []
        python_version: 3.10.16
        t:
            "1":
                - 1
                - 41
                - 55
            "2":
                - 1
                - 41
                - 55
            "3":
                - 13
                - 16
                - 23
                - 55
            "4": 3.10.16
            "5": 0.19.9
            "8":
                - 5
            "12": 0.19.9
            "13": linux-x86_64
data:
    value:
        batch_size: 64
        data_augmentation: vanilla
        data_root: ./data/
        dataset: CIFAR10
model:
    value:
        symmetry: vanilla
run:
    value:
        id: data_augmentation_test
        save_path: logs
        wandb_name: example_run
train:
    value:
        epochs: 1
        lr: 0.001
