data:
  augment_test: false
  batch_size: 256
  data_augmentation: vanilla
  data_root: ./data/
  dataset: CIFAR10
interpolation:
  num_samples: 10
  permutation_iter: 90
  method: QMC
models:
  name: ResNet18
  model_1: ./logs/vanilla/vanilla_1/final_model.pt
  model_2: ./logs/vanilla/rot90_1/final_model.pt
run:
  run_id: vanill_1_to_rot90_1_qmc
  save_dir: ./logs/vanilla_connectivity
