models:
  model_1: "./logs/vanilla_5/final_model.pt"
  model_2: "./logs/vflip_5/final_model.pt"
  name: "ResNet18"

interpolation:
  method: "LMCP"
  num_samples: 10
  permutation_iter : 90

data:
  dataset: "CIFAR10"
  data_root: "./data/"
  batch_size: 256
  data_augmentation: "vanilla"
  augment_test: false

run:
  save_dir: "./logs/connectivity"
  run_id: "vanilla_5_to_vflip_5_lmcp"
