_wandb:
    value:
        cli_version: 0.19.9
        m: []
        python_version: 3.10.16
        t:
            "1":
                - 1
                - 41
                - 55
            "2":
                - 1
                - 41
                - 55
            "3":
                - 13
                - 16
                - 23
                - 55
            "4": 3.10.16
            "5": 0.19.9
            "8":
                - 5
            "12": 0.19.9
            "13": linux-x86_64
data:
    value:
        augment_test: false
        batch_size: 256
        data_augmentation: vanilla
        data_root: ./data/
        dataset: CIFAR10
model:
    value:
        name: ResNet18
        symmetry: vanilla
run:
    value:
        id: vanilla
        save_path: logs
        wandb_name: ResNet_runs
train:
    value:
        base_lr: 0.1
        epochs: 5
        final_lr: 0.001
        momentum: 0.9
        weight_decay: 0.0001
